### ISSUE TITLE
不能同步空调状态

### ISSUE THREAD

**Issue by maxmib** [xcy1231/Ha-GreeCentralClimate#10]
使用最新版本插件支持云控二代后，homeassistant里的实体不能同步空调的实际状态，使用官方app或者空调面板控制空调后状态不会同步到homeassistant，即使通过homeassistant控制空调在homeassistant重启后实体状态也会变成默认的关闭。

**Comment by xcy1231** [comment]
上个日志看看哈

**Comment by xcy1231** [comment]
> > 上个日志看看哈
> 
> 云控二代官方升级固件后已经正常了，现在就是ha里偶尔会显示设备不可用，要重启ha才能恢复，云控应该是没有离线，官方app一直是正常

确实会出现400返回导致不可用的情况，但应该多等一会多同步几次就可以恢复的，可以上最新版多拉点日志看看
