### ISSUE TITLE
提问 代码添加位置

### ISSUE THREAD

**Issue by PANPINGLI** [xcy1231/Ha-GreeCentralClimate#13]
提问 二代云控  climate:
  - platform: gree2  这串代码添加到以下代码什么位置的呢。试了很多次 都无法在系统里面找到集成

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

**Comment by Chang228** [comment]
不用添加集成，在 实体里面直接就能看到

**Comment by xcy1231** [comment]
按readme操作就行吧，不需要找集成啊，找实体就好了
