### ISSUE TITLE
由于无法通过云控获得空调内置传感器温度，原本写死26度，现支持引入其他温度传感器展示到空调面板:

### ISSUE THREAD

**Issue by PANPINGLI** [xcy1231/Ha-GreeCentralClimate#15]
这个实测还是失败啊，改代码传感器，温度还是26℃ 写死，请问可以详细点吗，这个步骤，看有别的大神修改后也是如此

**Comment by xcy1231** [comment]
麻烦贴下你的配置代码啊

**Comment by PANPINGLI** [comment]
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate
climate:
  - platform: gree2 
climate:
  - platform: gree2
    temp_sensor:
      5e2b7f18000000_1: sensor.v1_cloud_d3aa22_id_1
      e4647e18000000_2: sensor.v1_cloud_d3a635_id_2
logger:
  default: warning
  logs:
    custom_components.gree2: debug
    custom_components.gree2.climate: debug
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
