### ISSUE TITLE
最新home assistant找不到实体

### ISSUE THREAD

**Issue by Yixi** [xcy1231/Ha-GreeCentralClimate#2]
最新版找不到实体了，能调整一下吗
HA版本0.112.2

**Comment by xcy1231** [comment]
我这边可以找到的，添加实体里面好像确实没有，添加温控器的卡片可以找到，还不行的话试试到格力+里面配置下分机的设备名称

**Comment by fenggegemen1** [comment]
Home Assistant 0.114.4版本中找不到实体，且温控器卡片也无法添加

**Comment by xcy1231** [comment]
云控返回的子设备名称都为格力空调，跟主设备相同，导致被过滤。改为名称+mac的方式，可能需要自己去对应查找空调是哪个房间的设备
