### ISSUE TITLE
2023.6不能用了吗

### ISSUE THREAD

**Issue by lhyfjzz** [xcy1231/Ha-GreeCentralClimate#24]
更新2023.6后不能用了

**Comment by cyanogenic** [comment]
2023.6 更新Python到3.11了，Python3.11移除了@asyncio.coroutine装饰器，可以参考下面这个

[https://github.com/cyanogenic/Ha-GreeCentralClimate/commit/7137644a0923aa73f07d551905c4798766e2d152](url)

**Comment by lhyfjzz** [comment]
好了，这样改一下就可以了
