### ISSUE TITLE
设置了外联的传感器后配置报错，没法重启，强制重启进入安全模式

### ISSUE THREAD

**Issue by style6** [xcy1231/Ha-GreeCentralClimate#25]
![2023616-215033](https://github.com/xcy1231/Ha-GreeCentralClimate/assets/47061418/3967e4c1-ccee-4cc0-b6a5-cf0793754cb5)
配置是直接黏贴过去的，格式应该没有问题，temp_sensor跟上一行只有一个空格是吗

**Comment by xcy1231** [comment]
temp_sensor前面不应该有一个空格的，文档有问题
