### ISSUE TITLE
是否支持格力云控二代

### ISSUE THREAD

**Issue by maxmib** [xcy1231/Ha-GreeCentralClimate#3]
添加插件后没有实体生成，空调开片里也找不到设备，使用的云控是二代云控长方形的，homeassistant版本Home Assistant 2021.3.2

**Comment by ddkens** [comment]
同问..

**Comment by xcy1231** [comment]
> 添加插件后没有实体生成，空调开片里也找不到设备，使用的云控是二代云控长方形的，homeassistant版本Home Assistant 2021.3.2

看别人贴的日志看起来好像可以响应，但是绑定这一步没走成功，我这边没有设备，也调试不了，不好意思啊
