### ISSUE TITLE
climate的turn_off服务调用似乎有点问题

### ISSUE THREAD

**Issue by dest16** [xcy1231/Ha-GreeCentralClimate#34]
用button_card开关空调发现的，用turn_off的服务调用就回报object has no attribute 'syncstate'，不是很懂ha的climate源码怎么处理的，对比了下hacs其他的空调插件，删除了device下的turn_off方法能正常关机不报错了，索性把turn_on方法也删除了，这下用button_card开关空调都没报错了

**Comment by xcy1231** [comment]
button_card是什么？看到这个turn_off服务顺手加上了，没想通怎么syncState大小写搞错了，现在应该可以了

**Comment by dest16** [comment]
ok，解决了
感谢~
