### ISSUE TITLE
格力的空调循环扇也能接入，能改成风扇模式吗？

### ISSUE THREAD

**Issue by hcfong2020** [xcy1231/Ha-GreeCentralClimate#35]
格力的空调循环扇也能接入，能改成风扇模式的集成吗？

**Comment by 234447388** [comment]
我这里有一个接不进去

**Comment by xcy1231** [comment]
用这个吧：https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent，这里主要针对中央空调
