### ISSUE TITLE
安装不生效，求解决

### ISSUE THREAD

**Issue by freshzhy** [xcy1231/Ha-GreeCentralClimate#39]
使用虚拟机安装ha
![image](https://github.com/xcy1231/Ha-GreeCentralClimate/assets/125800886/dcc9e0ca-04d9-437e-b168-fb5eba72f2f0)
文件夹已经放入/homeassistant/custom_components目录
![image](https://github.com/xcy1231/Ha-GreeCentralClimate/assets/125800886/e138294e-35bd-4db4-afbc-67eb185edeef)
configuration.yaml 文件已经添加
climate:
  - platform: gree2
 重启ha，无法找到设备,使用ha 添加，能够看到中央空调的组件，但无法添加。
![image](https://github.com/xcy1231/Ha-GreeCentralClimate/assets/125800886/fb31a8a8-fde3-4aeb-a9f8-54a15852450a)
不知道错误在哪，请大神告知。

**Comment by xcy1231** [comment]
麻烦先贴个日志

**Comment by freshzhy** [comment]
> 麻烦先贴个日志

![image](https://github.com/xcy1231/Ha-GreeCentralClimate/assets/125800886/ef8edaed-29bc-4e1f-81b8-90ba18c547b8)

**Comment by xcy1231** [comment]
这是没有搜索到云控，不填ip的话，ha的ip应该跟云控的ip同一网段。最好用最新版本，开启fakeserver，并且重置云控

**Comment by freshzhy** [comment]
> 这是没有搜索到云控，不填ip的话，ha的ip应该跟云控的ip同一网段。最好用最新版本，开启fakeserver，并且重置云控

云控与HA在同一局域网，填ip应该怎么填呢？另外，请问“在内网将dis.gree.com域名指向fake server的ip，也即HA服务器的ip”是否需要在路由器设置，重置云控后是不是就无法使用官方app了？

**Comment by freshzhy** [comment]
> 这是没有搜索到云控，不填ip的话，ha的ip应该跟云控的ip同一网段。最好用最新版本，开启fakeserver，并且重置云控

climate:
  - platform: gree2
    host: 192.168.1.100          这儿的host是否就填云控的ip呢

**Comment by xcy1231** [comment]
> > 这是没有搜索到云控，不填ip的话，ha的ip应该跟云控的ip同一网段。最好用最新版本，开启fakeserver，并且重置云控
> 
> climate:
> 
> * platform: gree2
>   host: 192.168.1.100          这儿的host是否就填云控的ip呢

对，使用fakeserver后就无法使用官方app了，可以在路由器中设置域名指向

**Comment by freshzhy** [comment]
先试了设置IP，路由器查询到了gree云控的ip
![image](https://github.com/xcy1231/Ha-GreeCentralClimate/assets/125800886/432007a5-c45e-4612-8e37-d2b9e6cca587)
重新配置了云控host的ip，暂时未设置fakeserver
![image](https://github.com/xcy1231/Ha-GreeCentralClimate/assets/125800886/ec2b0866-5f72-4382-bb42-3af78700af33)
仍然无反应
![image](https://github.com/xcy1231/Ha-GreeCentralClimate/assets/125800886/3c713773-9cb4-4c04-915d-0964a74affd1)

**Comment by xcy1231** [comment]
重置云控试过没？云控恢复出厂设置，重新通过格力+app添加设备，最新固件只能在这个时候响应 {"t":"scan"}的请求。如果还不行那我这边也不清楚什么情况了，是不是更新版的云控不支持这样的通信协议
