### ISSUE TITLE
安装后生成的实体超多

### ISSUE THREAD

**Issue by Colco** [xcy1231/Ha-GreeCentralClimate#40]
之前用过 这次升级HA 2024.1  这个也重新搞了一下  实际只有6个内机 生成了许多实体

**Comment by Colco** [comment]
<img width="827" alt="image" src="https://github.com/xcy1231/Ha-GreeCentralClimate/assets/12826994/aa1785b3-2bae-4295-8e4d-1ae6cb147d4e">

**Comment by Colco** [comment]
看了之前记录的ID 应该只有1a00000这种是对的

**Comment by xcy1231** [comment]
之前有个版本的云控固件确实会返回多余的mac地址，真实的设备可用的话应该也没有什么问题
