### ISSUE TITLE
HA Core 2024.5会导致插件失效

### ISSUE THREAD

**Issue by dw881114** [xcy1231/Ha-GreeCentralClimate#43]
二代云控，升级了2024.5的Core之后就识别不了了，需要回滚到2024.4之前的版本。大佬能看看是什么问题不？

**Comment by xcy1231** [comment]
前几天有个提交的，你拉最新的代码试试看

**Comment by dw881114** [comment]
> 前几天有个提交的，你拉最新的代码试试看

没问题了，感谢大佬
