### ISSUE TITLE
原来有一拖六，更新后3个没有了

### ISSUE THREAD

**Issue by lhyfjzz** [xcy1231/Ha-GreeCentralClimate#45]
![IMG_0128](https://github.com/xcy1231/Ha-GreeCentralClimate/assets/112108692/7bee388c-ec8c-4d56-9126-a27c3c79dd3a)
![IMG_0127](https://github.com/xcy1231/Ha-GreeCentralClimate/assets/112108692/7a71c2f3-21ca-47aa-bebe-248c54457013)

**Comment by xcy1231** [comment]
看实体id还是旧版的id，全清除掉再试试

**Comment by lhyfjzz** [comment]
删除集成重装也不行，后面找到去年的备份还原了，重新升级居然可以了

**Comment by xcy1231** [comment]
OK
