### ISSUE TITLE
怎么设置其他传感器做为当前温度

### ISSUE THREAD

**Issue by Yixi** [xcy1231/Ha-GreeCentralClimate#5]
换成了新的 gree2， 现在有个问题，怎么自定义空调卡片里面当前温度用其他的温度传感器呢？

**Comment by lwj1394** [comment]
遇到同样的问题。。不知道怎么解决

**Comment by lwj1394** [comment]
修改Gree2Climate.__init__方法，指定温湿度传感器实体就可以了。

**Comment by xcy1231** [comment]
这个我没太理解啊，这个空调卡片对应的就是空调传感器的温度，如果需要联动的话可以加其他的传感器卡片啊
