### ISSUE TITLE
七台分机只能发现五台

### ISSUE THREAD

**Issue by scythk** [xcy1231/Ha-GreeCentralClimate#6]
一共七台空调分机 安装插件后只能找到五台
在日志里也只能找到这五台的信息 没有其他错误信息
请问可能是哪里的问题呢

**Comment by xcy1231** [comment]
先贴个日志看看啊

**Comment by scythk** [comment]
[home-assistant.log](https://github.com/xcy1231/Ha-GreeCentralClimate/files/6823574/home-assistant.log)
日志见上
只能找到bd4dd71a000000 8772ce1a000000 461a031b000000 75cad31a000000 29b6061b000000这五个

**Comment by zxq321zxq** [comment]
我也是云控2代，6台只能搜到5台

**Comment by Colco** [comment]
同

**Comment by akakoori** [comment]
这个问题有人解决了吗。我家一拖六，我还没买云控，现在很慌

**Comment by zxq321zxq** [comment]
> 我家一拖六，我打算买云控，现在很慌张

没有解决，断电重新连接，可能就找到另外5个内机。反正就是总数5台内机。

**Comment by akakoori** [comment]
> > 我家一拖六，我打算买云控，现在很慌张
> 
> 没有解决，断电重新连接，可能就找到另外5个内机。反正就是总数5台内机。

手动添加第六台分机的mac是否可行？

**Comment by xcy1231** [comment]
可以试试，我只有4台分机，能拿到8台子设备，有4台无效，大概率解决了

**Comment by zxq321zxq** [comment]
> 我家一拖六，我打算买云控，现在很慌张

用了大佬5月20号的版本，现在能搜出6台内机了。
